Work on #86 and #114
OpenDroneMap/odm360 pull request #123
Opened 2020-10-30 17:08 UTC by hcwinsemius

I have solved the WiFi time out issue (tested on both child and parent side) #114 and have done some provisionary work on #86, the part on getting filenames from foreign tables and merging together.

2020-10-30 18:14 UTC, hcwinsemius commented
This issue also fixes #62.

2020-10-30 18:42 UTC, smathermather commented on provisioning/child_pi_setup.sh
> +sudo apt install -y postgresql-11-python3-multicorn
Are we adding multicorn back in, or is this a bit of legacy that didn't get removed?

2020-10-30 18:49 UTC, smathermather requested changes
Looks like we have some small legacy bits in here: some which reference usernames (Hi HCWincemius!) and a bit of File FDW sneaking its way back in. Otherwise, this looks good.

2020-10-30 18:49 UTC, smathermather commented on app.py
> +        z.write_iter("/home/hcwinsemius/temp/odm360/2.jpg", _generator("http://i.imgur.com/uAWnH3S.jpg"))
This seems legacy as well

2020-10-30 19:55 UTC, hcwinsemius commented on app.py
> +        z.write_iter("/home/hcwinsemius/temp/odm360/2.jpg", _generator("http://i.imgur.com/uAWnH3S.jpg"))
This is not a breaking thing but just a first bit of code to start zipstreaming. I suggest to just leave it for now so that I can work that out later.

2020-10-30 19:56 UTC, hcwinsemius commented on provisioning/child_pi_setup.sh
> +sudo apt install -y postgresql-11-python3-multicorn
Ahhh yeah....sorry about that. Not sure why this got re-introduced. Probably because of rebasing...

2020-10-31 14:06 UTC, ivangayton approved these changes
There's a lot going on here, but nothing that looks risky (some of is the same code deleted and re-added, presumably artifacts from reading). Merging on the understanding that of something goes wrong we'll fix it or revert if necessary!

2020-10-31 14:07 UTC, ivangayton commented
Merging, let's keep main up to date!

2020-10-31 14:08 UTC, merged

2020-11-01 10:03 UTC, hcwinsemius commented
Thank you @biglebowski